### ISSUE TITLE
Can't open app, for security reasons.

### ISSUE THREAD

**Issue by tarraq** [andrewn/brew-services-menubar#27]
Hello,

I'm trying to start the app, but get this message.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/1320993/156142063-3111b1a8-31c9-4e9b-8e5a-347f8b39a065.png">

I'm on OSX Monterey 12.2.1 on M1 chipset.

**Comment by stefansundin** [comment]
This appears because the app is not notarized by Apple. This requires paying Apple money and since it is a free program I am guessing it probably won't happen. Plus the extra work required to get it all set up.

You can run the application anyway by following the steps on Apple's website: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

Perhaps this could be explained in the README or in the release notes (or both!).

**Comment by andrewn** [comment]
Good idea. I [added a note to the readme](https://github.com/andrewn/brew-services-menubar/commit/4cb628d9c337adf36dfa100b8d28138fbee559fe).
